#pragma once

#define EE_HANDS
#define SPLIT_USB_DETECT

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_KEYPRESSES

#    define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#    define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS 128

#    define RGB_DISABLE_WHEN_USB_SUSPENDED
#endif
